### ISSUE TITLE
unable to install in linux

### ISSUE THREAD

**Issue by paulossant** [MjTs140914/PES_Stadium_Exporter#1]
When trying to install the addon I get the following error:

Traceback (most recent call last):
  File "/snap/blender/4166/4.1/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/home/paulo/.config/blender/4.1/scripts/addons/PES_Stadium_Exporter.py", line 4814, in register
    domData = minidom.parse(xml_dir+"PesFoxShader.xml")
  File "/snap/blender/4166/4.1/python/lib/python3.10/xml/dom/minidom.py", line 1990, in parse
    return expatbuilder.parse(file)
  File "/snap/blender/4166/4.1/python/lib/python3.10/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/paulo/.config/blender/4.1/scripts\\addons\\Tools\\Gzs\\xml\\PesFoxShader.xml'

How can I change the paths from using the "\\" to "/"?

**Comment by paulossant** [comment]
Nevermind, I just needed to extract the zip file and edit the "PES_Stadium_Exporter.py" by changing the following lines:
AddonsPath = str()
AddonsPath = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))
base_file_blend = '%s//addons//Tools//Gzs//base_file.blend' % AddonsPath
texconvTools = '"%s//addons//Tools//Gzs//texconv.exe"' % AddonsPath 
FtexTools ='"%s//addons//Tools//Gzs//FtexTools.exe"' % AddonsPath 
GZSPATH = '"%s//addons//Tools//Gzs//GzsTool.exe"' % AddonsPath 
foxTools = '"%s//addons//Tools//Gzs//FoxTool//FoxTool.exe"' % AddonsPath 
icons_dir = '%s//addons//Tools//Gzs//icons' % AddonsPath
xml_dir = '%s//addons//Tools//Gzs//xml//' % AddonsPath
lightFxPath = '%s//addons//Tools//Gzs//' % AddonsPath
baseStartupFile = '%s//addons//Tools//Gzs//startup.blend' % AddonsPath
startupFile = '%sconfig//startup.blend'%AddonsPath[:-7]
EnlightenPath="%s//addons//Tools//Gzs//EnlightenOutput//" % AddonsPath 
commonfile = "%s//addons//Tools//Gzs//xml//scarecrow//common" % AddonsPath 
csvPath = "%s//addons//Tools//Gzs//xml//Path.csv" % AddonsPath
